#_===========================================================================_#
#?                  ONLY USE THESE SERVICES IN DEVELOPMENT!                   #
#                                                                             #
#             !!! NEVER EXPOSE THESE SERVICES IN PRODUCTION! !!!              #
#_---------------------------------------------------------------------------_#
#  Info: Run the following command to create the .env file.                   #
#  Info: `cp MODEL.env .env`                                                  #
#  Info: Then update the values.                                              #
#_===========================================================================_#
services:
  #_===========================================================================_#
  #                                  DATABASE                                   #
  #_--------------------------------------------------------------------------_#
  mysql:
    image: mysql:8.0
    container_name: db_docker-mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?'MYSQL_ROOT_PASSWORD is not set'}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?'MYSQL_PASSWORD is not set'}
    volumes:
      - mysql_data:/var/lib/mysql
      - .docker/mysql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  #_===========================================================================_#
  #                                    TOOLS                                    #
  #_---------------------------------------------------------------------------_#
  phpmyadmin:
    build: .docker/phpma
    container_name: db_docker-phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER:-app_user}
      - PMA_PASSWORD=${MYSQL_PASSWORD:?'MYSQL_PASSWORD is not set'}
    depends_on:
      mysql:
        condition: service_healthy

#_=============================================================================_#
#                                    VOLUMES                                    #
#_-----------------------------------------------------------------------------_#
volumes:
  mysql_data:
    driver: local
