#_===========================================================================_#
#?                  ONLY USE THESE SERVICES IN DEVELOPMENT!                   #
#                                                                             #
#             !!! NEVER EXPOSE THESE SERVICES IN PRODUCTION! !!!              #
#_---------------------------------------------------------------------------_#
#  Info: Run the following command to create the .env file.                   #
#  Info: `cp MODEL.env .env`                                                  #
#  Info: Then update the values.                                              #
#_===========================================================================_#
services:
  #_===========================================================================_#
  #                                  DATABASES                                  #
  #_--------------------------------------------------------------------------  #                                                                             #
  #? Remember to:                                                               #
  #? - Update the .env file with the correct values.                            #
  #_===========================================================================_#
  mysql:
    image: mysql:9.6
    container_name: db_docker-mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?'MYSQL_ROOT_PASSWORD is not set'}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  #_===========================================================================_#
  #                                    TOOLS                                    #
  #_---------------------------------------------------------------------------_#
  # Tool for the MySQL database.                                                 #
  #_===========================================================================_#
  phpmyadmin:
    build:
      context: .docker/phpma
      network: host
    container_name: db_docker-phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    depends_on:
      mysql:
        condition: service_healthy

#_=============================================================================_#
#                                    VOLUMES                                    #
#_-----------------------------------------------------------------------------_#
#  Volume used by the MySQL database.                                            #
#_=============================================================================_#
volumes:
  mysql_data:
    driver: local
